import type {
  CodometerConfiguration,
  CodometerCustomStatistic,
} from "@codometer/configuration";

/**
 * What this package is measured by, and the first example it ships.
 *
 * Its presence is the configuration-discovery example: the workspace root
 * already carries a configuration that answers for every project beneath it,
 * and codometer takes the **first** file it finds walking upward — so this
 * one replaces it outright for this folder and everything beneath it that
 * declares no configuration of its own. Nothing from the root file is folded
 * in, which is why the conventions below are restated rather than imported.
 *
 * A configuration file authored as a function is no longer recognized, so
 * this is one plain object rather than a factory branching on which folder
 * was measured. That means a run measuring this package itself and a bare run
 * reached by walking upward from a folder beneath it — `examples/discovery`,
 * for instance — resolve to the exact same shape, `Corpus` target included.
 * See [`examples/discovery/README.md`](examples/discovery/README.md) for what
 * that means for a folder that is not the package root.
 */

// ♟️ Conventions

/** Name of the target holding the sample corpus, and the join key its limit is written against. */
const CORPUS_TARGET_NAME = "Corpus";

/**
 * The conventions the corpus was built to demonstrate.
 *
 * Two file-pattern counters over a corpus with stated counts, and one symbol
 * counter beside them. The corpus holds four `*.service.ts` files, six
 * `*.unit.test.ts` files, and four static methods — three in the services and
 * one in the JavaScript sample, because a symbol counter walks both
 * languages. A reader can check the tool agrees before declaring a counter of
 * their own.
 */
const conventions: CodometerCustomStatistic[] = [
  { label: "Service Files", patterns: ["**/*.service.ts"] },
  { label: "Unit Tests", patterns: ["**/*.unit.test.ts"] },
  {
    color: "166534",
    group: "typescript",
    label: "Static Methods",
    symbols: { kinds: ["method"], modifiers: ["static"] },
  },
];

/**
 * What a run measuring this package measures.
 *
 * The corpus is this package's equivalent of a compiled bundle: the thing it
 * ships, gated on its compressed size so a sample that grows without anybody
 * meaning it to is a failing check rather than a slow drift. Every input
 * carries the same conventions above, so a report from any folder this file
 * answers for shows the same badges.
 */
const conventionLabels = conventions.map((statistic) => statistic.label);

const codometerConfiguration: CodometerConfiguration = {
  custom: conventions,
  format: "markdown",
  inputs: [
    {
      analyses: ["size"],
      compression: "gzip",
      include: ["examples/corpus/**"],
      name: CORPUS_TARGET_NAME,
    },
  ],
  limits: [{ metric: `${CORPUS_TARGET_NAME}.size`, value: "24 KB" }],
  outputs: [
    {
      custom: conventionLabels,
      path: "codometer-report.json",
      type: "json",
    },
    {
      custom: conventionLabels,
      description:
        "Statistics for the sample corpus and the guides beside it, measured by [codometer](../codometer-cli), regenerated by `nx run codometer-examples:codometer:write`.",
      // Renamed for the reason this package documents: the README below
      // explains the default markers, so it holds `<!-- codometer:start -->` in
      // its own prose and a run using the defaults would splice the block into
      // the middle of the sentence describing them. Any document about
      // codometer has to rename its own markers, and this is that document.
      endMarker: "<!-- SAMPLE_STATISTICS_END -->",
      path: "README.md",
      startMarker: "<!-- SAMPLE_STATISTICS_START -->",
      type: "markdown",
    },
  ],
  // Python lives in a uv workspace, so the interpreter is reached through uv
  // rather than being on PATH — which the `examples/python` configurations
  // cover, and which is directly reusable by any repository whose Python is
  // behind a virtual environment.
  python: { command: "uv run python" },
};

export default codometerConfiguration;
