import { projectDefaults } from "../../../configuration/callidescope.config.js";

/**
 * What lexico-entities is held to, measured rather than assumed.
 *
 * Three frames. Entities and GraphQL types, so there is little here to call.
 *
 * Measured by a run scoped to this project and its dependency closure, and set
 * **at** what it measured rather than above it: a stack or a callable at either
 * limit passes, so this gate is green the day it arrives and each number is a
 * starting point to ratchet down from rather than a target to grow into.
 *
 * Three direct callees at the widest — ordinary fan-out rather than a closed
 * enumeration, so the next helper anybody extracts here is what moves the
 * number.
 *
 * @see configuration/callidescope.config.ts — `projectDefaults`, spread below
 * for everything this file does not override
 */
export default {
  ...projectDefaults,
  /**
   * The migrations. Generated by TypeORM, so their call stacks describe a
   * tool's output rather than anything a person structured — moved from
   * `configuration/.callidescopeignore`, the only project this path ever
   * matched.
   */
  exclude: ["src/modules/lexico-database/migrations/**"],
  limits: {
    maximumBreadth: 3,
    maximumDepth: 3,
  },
};
