export {
  CHECK_LIMITS,
  CHECK_NAMES,
  CHECK_REPORTS,
  CHECK_SEPARATOR,
  FORMAT_JSON,
  FORMAT_MARKDOWN,
  FORMAT_NAMES,
} from "./modules/configuration/configuration-flags.constants";
// 📤 Exports
export { codometerConfigurationSchema } from "./modules/configuration/configuration-schema.constants";
export {
  CODOMETER_ANALYSES,
  CODOMETER_COMMENT_LANGUAGES,
  CODOMETER_COMPRESSIONS,
  CODOMETER_DOCUMENTATION_UNITS,
  CODOMETER_FORMATS,
  CONFIGURATION_FILE_NAMES,
  DEFAULT_CODEBASE_INPUT,
  DEFAULT_CUSTOM_STATISTIC_COLORS,
  DEFAULT_CUSTOM_STATISTIC_GROUP,
  DEFAULT_EXCLUDE_GLOBS,
  DEFAULT_INPUT_COMPRESSION,
  DEFAULT_INPUT_DIRECTORY,
  DEFAULT_INPUT_NAME,
  DEFAULT_JSON_INDENTATION,
  DEFAULT_LIMIT_SEVERITY,
  DEFAULT_MARKDOWN_END_MARKER,
  DEFAULT_MARKDOWN_START_MARKER,
  DEFAULT_PYTHON_COMMAND,
  MISSING_FORMAT_MESSAGE,
  REPOSITORY_ROOT_MARKERS,
} from "./modules/configuration/configuration.constants";
export { ConfigurationModule } from "./modules/configuration/configuration.module";
export { ConfigurationService } from "./modules/configuration/configuration.service";
export type {
  CodometerAnalysis,
  CodometerCommentLanguage,
  CodometerCommentMeasurement,
  CodometerCommentSelector,
  CodometerCompression,
  CodometerConfiguration,
  CodometerCustomStatistic,
  CodometerDocumentationUnit,
  CodometerFormat,
  CodometerInput,
  CodometerJsonOutput,
  CodometerLimit,
  CodometerMarkdownOutput,
  CodometerOutput,
  CodometerPythonConfiguration,
  CodometerSymbolMatcher,
  LoadConfigurationArguments,
  MeasureCommandOptions,
  MeasureFormat,
  ModeSelection,
  RunMode,
} from "./modules/configuration/configuration.types";
export type {
  MarkdownAnchorHelpers,
  WriteMarkdownOutput,
  WriteMarkdownOutputArguments,
} from "./modules/configuration/output.types";
export type {
  LoadedConfiguration,
  ResolvedCodometerCommentSelector,
  ResolvedCodometerConfiguration,
  ResolvedCodometerCustomStatistic,
  ResolvedCodometerInput,
  ResolvedCodometerJsonOutput,
  ResolvedCodometerLimit,
  ResolvedCodometerMarkdownOutput,
  ResolvedCodometerOutput,
  ResolvedCodometerPythonConfiguration,
} from "./modules/configuration/resolved.types";
