import path from "node:path";
import { fileURLToPath } from "node:url";

import eslintReact from "@eslint-react/eslint-plugin";
import eslint from "@eslint/js";
import markdown from "@eslint/markdown";
import nxPlugin from "@nx/eslint-plugin";
import vitestPlugin from "@vitest/eslint-plugin";
import eslintConfigPrettier from "eslint-config-prettier";
import betterMaxParamsPlugin from "eslint-plugin-better-max-params";
import importPlugin from "eslint-plugin-import-x";
import jsdocPlugin from "eslint-plugin-jsdoc";
import jsoncPlugin from "eslint-plugin-jsonc";
import jsxA11yPlugin from "eslint-plugin-jsx-a11y";
import perfectionistPlugin from "eslint-plugin-perfectionist";
import {
  projectStructureParser,
  projectStructurePlugin,
} from "eslint-plugin-project-structure";
import tsdocPlugin from "eslint-plugin-tsdoc";
import eslintPluginUnicorn from "eslint-plugin-unicorn";
import eslintPluginYml from "eslint-plugin-yml";
import tseslint from "typescript-eslint";

import { conventionalLogMessagePlugin } from "@codebase/logging/eslint";

import type { ConfigWithExtends } from "typescript-eslint";

const folderStructureRule = projectStructurePlugin.rules["folder-structure"];

/**
 * `folder-structure`, rebound to markdown's syntax tree.
 *
 * The rule listens on `Program` and reads nothing but `context.filename`, so it
 * fires only on a file ESLint parsed into a JavaScript tree. Markdown is parsed
 * with `@eslint/markdown`'s `markdown/gfm` language, whose tree is mdast and
 * whose root node is `root` — so the visitor never runs and no markdown path is
 * ever checked.
 *
 * ESLint resolves exactly one `language` per file, so this cannot be fixed by
 * giving markdown a JavaScript parser: overriding `language` rejects the
 * markdown block's own `frontmatter` option outright, and leaving it alone
 * leaves the rule silently inert. Binding the same handler to `root` instead
 * puts both the markdown rules and the structure rule in one pass, which is why
 * this repository needs no second ESLint configuration for markdown.
 */
const markdownStructurePlugin = {
  rules: {
    "folder-structure": {
      ...folderStructureRule,
      create: (context: Parameters<typeof folderStructureRule.create>[0]) => {
        const { Program: judgePath } = folderStructureRule.create(context);

        return judgePath === undefined ? {} : { root: judgePath };
      },
    },
  },
};

const tsconfigRootDir = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);

export default [
  // 🚫 Global Ignores
  // Patterns excluded from ALL linting (build output, generated code, locks)
  {
    ignores: [
      "**/dist",
      "**/node_modules",
      "**/.venv",
      "**/coverage",
      "**/.conformetry",
      "**/.nx",
      "**/build",
      "**/tmp",
      "**/*.min.js",
      // Python tool caches — generated, gitignored, and never source. .pytest_cache
      // writes a README.md, which the root eslint target's `**/*.md` glob reaches
      "**/.pytest_cache/**",
      "**/.mypy_cache/**",
      "**/.ruff_cache/**",
      // Agent scratch space — gitignored (`.superpowers/sdd/.gitignore` is a
      // bare `*`) and never source, the same reason as the Python caches above
      "**/.superpowers/**",
      "**/vite.config.*.timestamp*",
      "**/vitest.config.*.timestamp*",
      "**/codometer-report.json",
      "CHANGELOG.md",
      "lint-staged.config.ts",
      // Shadcn generated components
      "**/packages/lexico-components/src/components/**",
      "**/packages/lexico-components/src/lib/**",
      "**/packages/lexico-components/src/hooks/**",
      // Lock files and Helm templates use formats that can't be linted
      "**/pnpm-lock.yaml",
      // skills-lock.json is machine-generated by the skills.sh CLI — key order is not controllable
      "skills-lock.json",
      "**/helm/**/templates/**",
      // Terraform providers and generated files
      "**/.terraform/**",
      // Symlinked mirrors of AGENTS.md — linted once at the source
      ".claude/CLAUDE.md",
      ".github/copilot-instructions.md",
      // Raw data folders (large JSON dumps, not source code)
      "**/data/wikipedia/**",
      "**/data/wiktionary/**",
      "**/data/library/**",
      "**/applications/lexico-ingestion/data/**",
      "**/applications/lexico-ingestion/src/modules/literature/literature.constants.ts",
      "**/applications/lexico-ingestion/src/modules/library/library.constants.ts",
      "**/library.json",
    ],
  },

  // 📂 Project Structure
  // Enforces folder architecture, kebab-case naming, and explicit abbreviation blocks
  {
    plugins: {
      "project-structure": projectStructurePlugin,
    },
    rules: {
      "project-structure/folder-structure": "error",
    },
    settings: {
      "project-structure/folder-structure-config-path":
        "configuration/codebase-structure.json",
    },
  },

  // 📄 HTML Placement
  // `.html` is matched by no other block, so ESLint never visits it and the
  // structure rule above never judges an HTML path — which is how a generated
  // `index.html` could have landed in a `src/` root unnoticed. Giving it a
  // parser that yields an empty `Program` is enough: the structure rule reads
  // only the path, so nothing here parses HTML or pretends to.
  //
  // Markdown needs a different treatment — see 📝 Markdown Placement below,
  // which rebinds the same rule to mdast's root node rather than re-parsing.
  {
    files: ["**/*.html"],
    languageOptions: {
      parser: projectStructureParser,
    },
  },

  // 📢 Logger Convention
  // Statically flags a log call whose message doesn't start with an emoji
  // naming its subject, then a verb in present progressive or past tense —
  // the same convention `LoggerService` enforces at runtime. Test files are
  // excluded: they deliberately construct malformed messages to exercise the
  // runtime check's own production/context exemptions, and a static rule
  // flagging that fixture data would be noise, not signal.
  {
    files: [
      "**/*.ts",
      "**/*.tsx",
      "**/*.mts",
      "**/*.cts",
      "**/*.js",
      "**/*.mjs",
      "**/*.cjs",
      "**/*.jsx",
    ],
    ignores: [
      "**/*.test.ts",
      "**/*.test.tsx",
      "**/testing/**",
      "**/__tests__/**",
    ],
    plugins: {
      "logger-convention": conventionalLogMessagePlugin,
    },
    rules: {
      "logger-convention/conventional-log-message": "error",
    },
  },

  // ✅ Base ESLint Recommended
  // Core ESLint recommended rules applied to all non-markdown source files
  {
    ...eslint.configs.recommended,
    files: [
      "**/*.ts",
      "**/*.tsx",
      "**/*.mts",
      "**/*.cts",
      "**/*.js",
      "**/*.mjs",
      "**/*.cjs",
      "**/*.jsx",
      "**/*.json",
      "**/*.jsonc",
      "**/*.json5",
      "**/*.yaml",
      "**/*.yml",
    ],
  },

  // 🏗️ Nx Plugin
  // Module boundary enforcement and dependency validation
  ...nxPlugin.configs["flat/base"],
  ...nxPlugin.configs["flat/typescript"],
  ...nxPlugin.configs["flat/javascript"],

  // 🦄 Unicorn Recommended Rules
  // Code quality and modern JavaScript patterns
  {
    ...eslintPluginUnicorn.configs.recommended,
    files: [
      "**/*.ts",
      "**/*.tsx",
      "**/*.mts",
      "**/*.cts",
      "**/*.js",
      "**/*.mjs",
      "**/*.cjs",
      "**/*.jsx",
    ],
  },

  // 🦄 Unicorn Rule Overrides
  // Disable rules that conflict with existing conventions
  {
    files: [
      "**/*.ts",
      "**/*.tsx",
      "**/*.mts",
      "**/*.cts",
      "**/*.js",
      "**/*.mjs",
      "**/*.cjs",
      "**/*.jsx",
    ],
    rules: {
      // PascalCase React components and kebab-case filenames are used throughout
      "unicorn/filename-case": "off",
      // null is used extensively in the codebase (React refs, database nulls, API contracts)
      "unicorn/no-null": "off",
      // Abbreviations are banned per ESLint and CSpell config — only `args` and `str` are acceptable
      "unicorn/prevent-abbreviations": [
        "warn",
        {
          allowList: {
            // args: `arguments` is a reserved keyword in JavaScript
            args: true,
            // charSet: TanStack Router meta API property name (external interface contract)
            charSet: true,
            // envFilePath: NestJS ConfigModule.forRoot API property name (external interface contract)
            envFilePath: true,
            // rel: TanStack Router meta API property name (external interface contract)
            rel: true,
            // str: `string` is a reserved keyword in TypeScript
            str: true,
          },
          checkDefaultAndNamespaceImports: true,
          checkFilenames: false,
          checkProperties: true,
          checkShorthandImports: true,
          checkShorthandProperties: true,
          checkVariables: true,
          ignore: [
            /\.e2e$/,
            /\.cjs$/,
            /\.mjs$/,
            /\.d\.ts$/,
            /vite\.config\..*$/,
            /vitest\.config\..*$/,
            /eslint\.config\..*$/,
            /package\.json/,
            // React component property type names use the standard `Props` suffix
            /\w+Props$/,
          ],
          // The map spells out every abbreviation CSpell's `flagWords` also bans.
          // cspell:disable
          replacements: {
            app: { application: true },
            arr: { array: true },
            auth: { authentication: true, authorization: true },
            bg: { background: true },
            bool: { boolean: true },
            char: { character: true },
            col: { column: true },
            ctx: { context: true },
            cur: { current: true },
            curr: { current: true },
            db: { database: true },
            decl: { declaration: true },
            dev: { development: true },
            dir: { directory: true },
            e: { error: true, event: true },
            el: { element: true },
            env: { environment: true },
            fn: { function: true },
            hex: { hexadecimal: true },
            i: { index: true },
            idx: { index: true },
            j: { index: true },
            k: { index: true },
            max: { maximum: true },
            min: { minimum: true },
            nav: { navigation: true },
            num: { number: true },
            obj: { object: true },
            param: { parameter: true },
            pkg: { package: true },
            prod: { production: true },
            px: { pixel: true },
            rel: { relative: true },
            req: { request: true },
            res: { response: true },
            ret: { return: true },
            src: { source: true },
            stg: { staging: true },
            temp: { temporary: true },
            tmp: { temporary: true },
            txt: { text: true },
            util: { utility: true },
            val: { value: true },
          },
          // cspell:enable
        },
      ],
      // reduce() is used in pipeline transformations and aggregations
      "unicorn/no-array-reduce": "off",
      // forEach() is acceptable for imperative operations with side effects
      "unicorn/no-array-for-each": "off",
      // CJS config files exist (.cjs extensions for tools that don't support ESM)
      "unicorn/prefer-module": "off",
      // CLI applications (caelundas) use process.exit() for clean shutdown
      "unicorn/no-process-exit": "off",
      // Not all entry points support top-level await (CJS configs, legacy tooling)
      "unicorn/prefer-top-level-await": "off",
      // ESLint core rule no-nested-ternary already handles this
      "unicorn/no-nested-ternary": "off",
      // Placeholder files with only a comment header are intentional
      "unicorn/no-empty-file": "off",
      // Preserve readability for long numeric literals with separators
      "unicorn/numeric-separators-style": "off",
    },
  },

  // 🦄 Unicorn Test File Relaxations
  // Allow test-specific patterns
  {
    files: ["**/*.test.ts", "**/testing/**"],
    rules: {
      // Test helpers are often defined inline for clarity
      "unicorn/consistent-function-scoping": "off",
      // Explicit undefined in test assertions is acceptable
      "unicorn/no-useless-undefined": "off",
      // Abbreviation rules are too strict for test files (e.g. catch (e), mock variable names)
      "unicorn/prevent-abbreviations": "off",
    },
  },

  // 🦄 Unicorn Config File Relaxations
  // Allow CommonJS patterns in config files
  {
    files: [
      "**/*.js",
      "**/*.mjs",
      "**/*.cjs",
      "**/*.config.ts",
      "**/*.config.mts",
      "**/vite.config.*",
      "**/vitest.config.*",
      "**/eslint.config.*",
    ],
    rules: {
      // Config files explicitly use .cjs extension when CommonJS is required
      "unicorn/prefer-module": "off",
      // Config files often use schema-defined property names that are abbreviations
      "unicorn/prevent-abbreviations": "off",
    },
  },

  // ⚙️ Main Configuration
  // Core rules for all TS/JS source files: module boundaries, import ordering,
  // strict TypeScript type safety, naming conventions, and best practices
  {
    files: [
      "**/*.ts",
      "**/*.tsx",
      "**/*.mts",
      "**/*.cts",
      "**/*.js",
      "**/*.mjs",
      "**/*.cjs",
      "**/*.jsx",
    ],
    ignores: [
      "lint-staged.config.ts",
      "prettier.config.ts",
      "configuration/eslint.config.ts",
    ],
    plugins: {
      "@typescript-eslint": tseslint.plugin,
      "better-max-params": betterMaxParamsPlugin,
      import: importPlugin,
      perfectionist: perfectionistPlugin,
    },
    rules: {
      "@nx/dependency-checks": [
        "error",
        {
          ignoredDependencies: ["@codebase/logging"],
        },
      ],
      "@nx/enforce-module-boundaries": [
        "error",
        {
          depConstraints: [
            {
              onlyDependOnLibsWithTags: ["type:package"],
              sourceTag: "type:application",
            },
            // Callidescope package graph. Core, holding the domain vocabulary
            // and nothing executable, is the leaf; the configuration package
            // resolves the file and the flags over it; the graph builder
            // analyzes; the output renderer depends on the configuration and
            // the graph it renders; the CLI composes them, so the dependency
            // only ever points that way.
            {
              onlyDependOnLibsWithTags: [],
              sourceTag: "name:callidescope-core",
            },
            {
              onlyDependOnLibsWithTags: [
                "name:callidescope-core",
                "name:logger",
              ],
              sourceTag: "name:callidescope-configuration",
            },
            {
              onlyDependOnLibsWithTags: [
                "name:callidescope-configuration",
                "name:callidescope-core",
                "name:logger",
              ],
              sourceTag: "name:callidescope-graph",
            },
            {
              onlyDependOnLibsWithTags: [
                "name:callidescope-configuration",
                "name:callidescope-core",
                "name:callidescope-graph",
                "name:logger",
              ],
              sourceTag: "name:callidescope-output",
            },
            {
              onlyDependOnLibsWithTags: [
                "name:callidescope-configuration",
                "name:callidescope-core",
                "name:callidescope-graph",
                "name:callidescope-output",
                "name:logger",
              ],
              sourceTag: "name:callidescope-cli",
            },
            // The Nx plugin sits on top of the whole chain and nothing in the
            // chain may depend back on it, which is what keeps `@nx/devkit`
            // out of every package that actually traces. It is the only
            // callidescope package Nx is allowed to reach.
            {
              onlyDependOnLibsWithTags: [
                "name:callidescope-cli",
                "name:callidescope-configuration",
                "name:callidescope-core",
                "name:callidescope-graph",
                "name:callidescope-output",
                "name:logger",
              ],
              sourceTag: "name:callidescope-nx",
            },
            // Codometer package graph, on the ic-suite five-layer spine:
            // `core <- configuration <- measurement <- output <- cli`. The
            // contracts leaf holds the measured vocabulary and depends on
            // nothing; configuration resolves the config file and the command
            // line over it; the language analyzers and the measurement
            // package do the measuring; output owns every render target,
            // report diffing included; and the command-line host wires
            // commands over all of them.
            {
              onlyDependOnLibsWithTags: [],
              sourceTag: "name:codometer-core",
            },
            {
              onlyDependOnLibsWithTags: ["name:codometer-core"],
              sourceTag: "name:codometer-configuration",
            },
            {
              onlyDependOnLibsWithTags: [
                "name:codometer-configuration",
                "name:codometer-core",
                "name:logger",
              ],
              sourceTag: "name:codometer-languages",
            },
            {
              onlyDependOnLibsWithTags: [
                "name:codometer-configuration",
                "name:codometer-core",
                "name:codometer-languages",
                "name:logger",
              ],
              sourceTag: "name:codometer-measurement",
            },
            {
              onlyDependOnLibsWithTags: [
                "name:codometer-configuration",
                "name:codometer-core",
                "name:codometer-measurement",
                "name:logger",
              ],
              sourceTag: "name:codometer-output",
            },
            {
              onlyDependOnLibsWithTags: [
                "name:codometer-configuration",
                "name:codometer-core",
                "name:codometer-measurement",
                "name:codometer-output",
                "name:logger",
              ],
              sourceTag: "name:codometer-cli",
            },
            // Conformetry package graph, on the ic-suite five-layer spine:
            // core, configuration, analysis, output, cli. `conformetry-core`
            // is the contracts leaf and holds no service, so nothing above it
            // has to be dragged in to import a type; placeholder rendering
            // lives in the configuration layer, because substituting a
            // template or instance path is part of resolving it, and
            // `conformetry-generation` consumes it upward.
            {
              onlyDependOnLibsWithTags: [],
              sourceTag: "name:conformetry-core",
            },
            {
              onlyDependOnLibsWithTags: ["name:conformetry-core"],
              sourceTag: "name:conformetry-configuration",
            },
            {
              onlyDependOnLibsWithTags: [
                "name:conformetry-configuration",
                "name:conformetry-core",
              ],
              sourceTag: "name:conformetry-generation",
            },
            // One rule for every Language, because they are one package: the
            // Languages sit in `conformetry-languages`, alongside the
            // extension-agnostic existence pass and the difference and
            // scoring primitives every validator shares. Jupyter's delegation
            // to JSON, markdown, and Python is an intra-package import, which
            // neither this rule nor codependix polices — accepted, and
            // recorded as such.
            {
              onlyDependOnLibsWithTags: [
                "name:conformetry-configuration",
                "name:conformetry-core",
              ],
              sourceTag: "name:conformetry-languages",
            },
            {
              onlyDependOnLibsWithTags: [
                "name:conformetry-configuration",
                "name:conformetry-core",
                "name:conformetry-languages",
              ],
              sourceTag: "name:conformetry-validation",
            },
            {
              onlyDependOnLibsWithTags: [
                "name:conformetry-core",
                "name:conformetry-languages",
                "name:conformetry-validation",
              ],
              sourceTag: "name:conformetry-output",
            },
            {
              onlyDependOnLibsWithTags: [
                "name:conformetry-configuration",
                "name:conformetry-core",
                "name:conformetry-generation",
                "name:conformetry-output",
                "name:conformetry-validation",
                "name:logger",
              ],
              sourceTag: "name:conformetry",
            },
            {
              onlyDependOnLibsWithTags: [
                "name:conformetry-configuration",
                "name:conformetry-core",
                "name:conformetry-generation",
                "name:conformetry-output",
                "name:conformetry-validation",
                "name:logger",
              ],
              sourceTag: "name:conformetry-nx",
            },
            // The examples package demonstrates the whole toolchain, so it sits
            // above every runtime package and above the Nx host. It may not
            // depend on `name:conformetry` — the command-line host — which is
            // the claim its embedding example makes: the CLI holds no logic of
            // its own, so nothing ever needs to import it.
            {
              onlyDependOnLibsWithTags: [
                "name:conformetry-configuration",
                "name:conformetry-core",
                "name:conformetry-generation",
                "name:conformetry-nx",
                "name:conformetry-output",
                "name:conformetry-validation",
              ],
              sourceTag: "name:conformetry-examples",
            },
            {
              notDependOnLibsWithTags: ["type:application"],
              sourceTag: "type:package",
            },
            {
              notDependOnLibsWithTags: ["framework:nestjs"],
              sourceTag: "framework:react",
            },
            {
              notDependOnLibsWithTags: ["domain:lexico"],
              sourceTag: "domain:caelundas",
            },
            {
              notDependOnLibsWithTags: ["domain:caelundas"],
              sourceTag: "domain:lexico",
            },
          ],
          enforceBuildableLibDependency: true,
        },
      ],

      "import/default": "off", // TypeScript handles this
      "import/named": "off", // TypeScript handles this
      "import/namespace": "off", // TypeScript handles this
      "import/no-duplicates": "error",
      "import/no-named-as-default-member": "off", // TypeScript handles this
      "import/no-relative-packages": "error",
      "import/no-relative-parent-imports": "warn",
      "import/no-unresolved": "off", // TypeScript handles this
      "perfectionist/sort-array-includes": [
        "error",
        { order: "asc", type: "natural" },
      ],
      "perfectionist/sort-arrays": ["off"],
      "perfectionist/sort-classes": [
        "error",
        {
          groups: [
            "constructor",
            "index-signature",
            "static-property",
            "static-block",
            "private-property",
            "protected-property",
            "property",
            "accessor-property",
            "static-method",
            "private-method",
            "protected-method",
            "get-method",
            "set-method",
            "method",
          ],
          order: "asc",
          type: "natural",
        },
      ],
      "perfectionist/sort-decorators": [
        "error",
        { order: "asc", partitionByNewLine: true, type: "natural" },
      ],
      "perfectionist/sort-enums": [
        "error",
        { order: "asc", partitionByNewLine: true, type: "natural" },
      ],
      "perfectionist/sort-export-attributes": [
        "error",
        { order: "asc", type: "natural" },
      ],
      "perfectionist/sort-exports": [
        "error",
        { order: "asc", type: "natural" },
      ],
      "perfectionist/sort-heritage-clauses": [
        "error",
        { order: "asc", type: "natural" },
      ],
      "perfectionist/sort-import-attributes": [
        "error",
        { order: "asc", type: "natural" },
      ],
      "perfectionist/sort-imports": [
        "error",
        {
          groups: [
            "builtin",
            "external",
            "internal",
            "parent",
            "sibling",
            "index",
            "type",
          ],
          ignoreCase: true,
          internalPattern: ["^@codebase/.+"],
          newlinesBetween: 1,
          order: "asc",
          type: "natural",
        },
      ],
      "perfectionist/sort-interfaces": [
        "error",
        { order: "asc", type: "natural" },
      ],
      "perfectionist/sort-intersection-types": [
        "error",
        { order: "asc", type: "natural" },
      ],
      "perfectionist/sort-maps": ["error", { order: "asc", type: "natural" }],
      "perfectionist/sort-modules": [
        "error",
        {
          groups: [
            "declare-enum",
            "export-enum",
            "enum",
            ["declare-interface", "declare-type"],
            ["export-interface", "export-type"],
            ["interface", "type"],
            "declare-class",
            "class",
            "export-class",
            "declare-function",
            "export-function",
            "function",
          ],
          order: "asc",
          type: "natural",
        },
      ],
      "perfectionist/sort-named-exports": [
        "error",
        { order: "asc", type: "natural" },
      ],
      "perfectionist/sort-named-imports": [
        "error",
        { order: "asc", type: "natural" },
      ],
      "perfectionist/sort-object-types": [
        "error",
        { order: "asc", type: "natural" },
      ],
      "perfectionist/sort-objects": [
        "error",
        {
          order: "asc",
          partitionByComment: true,
          partitionByNewLine: true,
          type: "natural",
        },
      ],
      "perfectionist/sort-sets": ["error", { order: "asc", type: "natural" }],
      "perfectionist/sort-switch-case": [
        "error",
        { order: "asc", type: "natural" },
      ],
      "perfectionist/sort-union-types": [
        "error",
        { order: "asc", type: "natural" },
      ],
      "perfectionist/sort-variable-declarations": [
        "error",
        { order: "asc", type: "natural" },
      ],

      // Strict TypeScript rules
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/consistent-type-exports": [
        "error",
        {
          fixMixedExportsWithInlineTypeSpecifier: true,
        },
      ],
      "@typescript-eslint/consistent-type-imports": [
        "error",
        {
          fixStyle: "inline-type-imports",
          prefer: "type-imports",
        },
      ],
      "@typescript-eslint/explicit-function-return-type": [
        "error",
        {
          allowExpressions: true,
          allowHigherOrderFunctions: true,
          allowTypedFunctionExpressions: true,
        },
      ],
      "@typescript-eslint/explicit-module-boundary-types": "error",
      "@typescript-eslint/naming-convention": [
        "error",
        {
          filter: {
            match: false,
            regex: "^(_|__(filename|dirname))$",
          },
          format: ["camelCase"],
          selector: "default",
        },
        {
          filter: {
            match: false,
            regex: "^__(filename|dirname)$",
          },
          format: ["camelCase", "UPPER_CASE", "PascalCase"],
          selector: "variable",
        },
        {
          format: ["camelCase", "PascalCase"],
          selector: "function",
        },
        {
          format: ["PascalCase"],
          selector: "typeLike",
        },
        {
          format: ["UPPER_CASE"],
          selector: "enumMember",
        },
        {
          filter: {
            match: false,
            regex: "^_$",
          },
          format: ["camelCase", "PascalCase"],
          selector: "import",
        },
        {
          filter: {
            match: false,
            regex: "^_$",
          },
          format: ["camelCase"],
          leadingUnderscore: "allow",
          selector: "parameter",
        },
        {
          format: null,
          selector: "objectLiteralProperty",
        },
      ],
      "@typescript-eslint/no-confusing-void-expression": [
        "error",
        { ignoreArrowShorthand: true, ignoreVoidOperator: true },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-import-type-side-effects": "error",
      "@typescript-eslint/no-meaningless-void-operator": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/no-unnecessary-type-assertion": "error",
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-return": "error",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      "@typescript-eslint/prefer-optional-chain": "error",
      "@typescript-eslint/prefer-readonly": "error",
      "@typescript-eslint/prefer-reduce-type-parameter": "error",
      "@typescript-eslint/prefer-return-this-type": "error",
      "@typescript-eslint/promise-function-async": "error",
      "@typescript-eslint/require-await": "error",
      "@typescript-eslint/restrict-template-expressions": "off",
      "@typescript-eslint/strict-boolean-expressions": "off",
      "@typescript-eslint/switch-exhaustiveness-check": "error",

      // General best practices
      "@typescript-eslint/no-unused-expressions": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/only-throw-error": "error",
      "array-callback-return": "error",
      "better-max-params/better-max-params": [
        "error",
        { constructor: 12, func: 3 },
      ],
      complexity: ["warn", { max: 8 }],
      curly: ["error", "all"],
      eqeqeq: ["error", "always"],
      "grouped-accessor-pairs": ["error", "getBeforeSet"],
      "max-classes-per-file": ["error", { ignoreExpressions: true, max: 1 }],
      "max-depth": ["error", { max: 4 }],
      "max-lines": ["error", { max: 512 }],
      "max-lines-per-function": ["error", { max: 128 }],
      "max-nested-callbacks": ["error", { max: 3 }],
      "max-params": "off", // replaced by better-max-params/better-max-params
      "max-statements": ["error", { max: 16 }],
      "no-alert": "error",
      "no-console": ["warn", { allow: ["warn", "error", "info"] }],
      "no-constructor-return": "error",
      "no-debugger": "error",
      "no-duplicate-imports": "off", // import/no-duplicates handles this
      "no-else-return": ["warn", { allowElseIf: false }],
      "no-implicit-coercion": ["error", { allow: ["!!"] }],
      "no-lone-blocks": "error",
      "no-loop-func": "off", // @typescript-eslint/no-loop-func handles this
      "no-param-reassign": "warn",
      "no-promise-executor-return": "error",
      "no-restricted-syntax": [
        "error",
        {
          message:
            "for..in iterates over the prototype chain. Use Object.{keys,values,entries} instead.",
          selector: "ForInStatement",
        },
        {
          message:
            "Labels create confusing control flow. Use named functions or early returns instead.",
          selector: "LabeledStatement",
        },
        {
          message: "'with' is disallowed in strict mode.",
          selector: "WithStatement",
        },
      ],
      "no-self-compare": "error",
      "no-shadow": "off", // @typescript-eslint/no-shadow handles this
      "no-throw-literal": "off", // TypeScript ESLint handles this
      "no-unreachable-loop": "error",
      "no-unused-expressions": "off", // TypeScript ESLint handles this
      "no-unused-vars": "off", // TypeScript ESLint handles this
      "no-useless-concat": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "object-shorthand": ["error", "always"],
      "prefer-arrow-callback": "error",
      "prefer-const": "error",
      "prefer-object-spread": "error",
      "prefer-template": "error",
      radix: "error",
      yoda: ["error", "never"],
    },
  },

  // 🪺 Nest Module Provider Overrides
  // NestJS module metadata can legitimately include provider factory functions
  // with many injected dependencies; allow more parameters in *.module.ts files.
  {
    files: ["**/*.module.ts"],
    rules: {
      "better-max-params/better-max-params": [
        "warn",
        { constructor: 12, func: 12 },
      ],
    },
  },

  // 🧭 Nest Class File Shape
  // Command, service, resolver, and loader files should expose only
  // their class at the top level.
  // Move top-level helpers to *.constants.ts or *.types.ts, or into class members.
  {
    files: [
      "**/*.command.ts",
      "**/*.loader.ts",
      "**/*.module.ts",
      "**/*.resolver.ts",
      "**/*.service.ts",
    ],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          message:
            "Only imports and a single top-level class are allowed in NestJS class files. Move top-level symbols onto the class or out to *.constants.ts or *.types.ts.",
          selector:
            "Program > :not(ImportDeclaration):not(ClassDeclaration):not(ExportNamedDeclaration[declaration.type='ClassDeclaration']):not(ExportDefaultDeclaration[declaration.type='ClassDeclaration'])",
        },
      ],
    },
  },

  // 🏷️ Type File Shape
  // Type files should expose only imports plus top-level types and interfaces.
  {
    files: ["**/*.types.ts"],
    ignores: [
      "**/applications/caelundas/src/modules/caelundas/caelundas.types.ts",
      "**/src/modules/caelundas/caelundas.types.ts",
      "applications/caelundas/src/modules/caelundas/caelundas.types.ts",
    ],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          message:
            "Only imports, interfaces, and type aliases are allowed in type files. Move other symbols to dedicated files.",
          selector:
            "Program > :not(ImportDeclaration):not(TSInterfaceDeclaration):not(TSTypeAliasDeclaration):not(ExportNamedDeclaration[declaration.type='TSInterfaceDeclaration']):not(ExportNamedDeclaration[declaration.type='TSTypeAliasDeclaration'])",
        },
      ],
    },
  },

  // 🧱 Constant File Shape
  // Constant files should expose only imports plus top-level const declarations,
  // and the error classes thrown from beside them.
  {
    files: ["**/*.constants.ts"],
    ignores: [
      "**/applications/caelundas/src/modules/caelundas/caelundas.constants.ts",
      "**/applications/caelundas/src/modules/ephemeris/ephemeris.constants.ts",
      "**/applications/lexico-ingestion/src/modules/forms/forms.constants.ts",
      "**/applications/lexico-ingestion/src/modules/manual/manual.constants.ts",
      "**/applications/lexico-ingestion/src/modules/part-of-speech/part-of-speech.constants.ts",
      "**/packages/lexico-entities/src/modules/database/database.constants.ts",
      "**/src/modules/caelundas/caelundas.constants.ts",
      "**/src/modules/database/database.constants.ts",
      "**/src/modules/ephemeris/ephemeris.constants.ts",
      "**/src/modules/forms/forms.constants.ts",
      "**/src/modules/manual/manual.constants.ts",
      "**/src/modules/part-of-speech/part-of-speech.constants.ts",
      "**/src/modules/validator/validator.constants.ts",
    ],
    rules: {
      // The selector below is the guard that makes this safe: the only class a
      // constants file may declare is one extending `Error`, so lifting the
      // count permits several error classes and nothing else. A module whose
      // errors are one class per cause — meanderaw's five — can then keep them
      // distinct in the one constants file beside the code that throws them.
      "max-classes-per-file": "off",
      "no-restricted-syntax": [
        "error",
        {
          message:
            "Only imports and const declarations are allowed in constant files. Move other top-level symbols to dedicated files.",
          selector:
            "Program > :not(ImportDeclaration):not(VariableDeclaration[kind='const']):not(ExportNamedDeclaration[declaration.type='VariableDeclaration'][declaration.kind='const']):not(ExportDefaultDeclaration[declaration.type='VariableDeclaration'][declaration.kind='const']):not(ClassDeclaration[superClass.type='Identifier'][superClass.name='Error']):not(ExportNamedDeclaration[declaration.type='ClassDeclaration'][declaration.superClass.type='Identifier'][declaration.superClass.name='Error']):not(ExportDefaultDeclaration[declaration.type='ClassDeclaration'][declaration.superClass.type='Identifier'][declaration.superClass.name='Error'])",
        },
      ],
    },
  },

  // 🛠️ Utility File Shape
  // Utility files should expose only imports plus top-level functions.
  {
    files: ["**/*.utilities.ts"],
    ignores: [
      "**/applications/caelundas/testing/aspect-test.utilities.ts",
      "**/testing/aspect-test.utilities.ts",
    ],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          message:
            "Only imports and function declarations are allowed in utility files. Move other top-level symbols to dedicated files.",
          selector:
            "Program > :not(ImportDeclaration):not(FunctionDeclaration):not(ExportNamedDeclaration[declaration.type='FunctionDeclaration']):not(ExportDefaultDeclaration[declaration.type='FunctionDeclaration'])",
        },
      ],
    },
  },

  // 🔷 TypeScript Strict Type-Checked
  // Enables strict + stylistic type-checked rule sets from typescript-eslint.
  // Requires parserOptions.projectService for type-aware linting.
  ...tseslint.configs.strictTypeChecked.map((config) => ({
    ...config,
    files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
    ignores: ["lint-staged.config.ts", "prettier.config.ts"],
  })),
  ...tseslint.configs.stylisticTypeChecked.map((config) => ({
    ...config,
    files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
    ignores: ["lint-staged.config.ts", "prettier.config.ts"],
  })),
  {
    files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
    ignores: ["lint-staged.config.ts", "prettier.config.ts"],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir,
      },
    },
    plugins: {
      "@typescript-eslint": tseslint.plugin,
    },
    rules: {
      "@typescript-eslint/consistent-return": "error",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/no-extraneous-class": [
        "error",
        { allowWithDecorator: true },
      ],
      "@typescript-eslint/no-loop-func": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-shadow": "error",
      "@typescript-eslint/no-useless-constructor": "off",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      "@typescript-eslint/restrict-template-expressions": "off",
    },
  },

  // 📚 TSDoc / JSDoc Documentation
  // Enforces TSDoc syntax, broad JSDoc coverage (including private APIs),
  // TypeScript-aware tag hygiene, and sentence-quality descriptions.
  {
    files: ["**/*.ts", "**/*.tsx"],
    ignores: [
      "**/*.test.ts",
      "**/*.test.tsx",
      "lint-staged.config.ts",
      "prettier.config.ts",
    ],
    plugins: {
      jsdoc: jsdocPlugin,
      tsdoc: tsdocPlugin,
    },
    rules: {
      "jsdoc/check-tag-names": ["warn", { typed: true }],
      "jsdoc/no-blank-blocks": "error",
      "jsdoc/require-description": "warn",
      "jsdoc/require-jsdoc": [
        "error",
        {
          checkConstructors: false,
          contexts: [
            "TSInterfaceDeclaration",
            "TSTypeAliasDeclaration",
            "TSEnumDeclaration",
          ],
          exemptEmptyConstructors: true,
          exemptEmptyFunctions: false,
          publicOnly: false,
          require: {
            ArrowFunctionExpression: false,
            ClassDeclaration: true,
            FunctionDeclaration: true,
            FunctionExpression: false,
            MethodDefinition: true,
          },
        },
      ],
      "tsdoc/syntax": "warn",
    },
    settings: { jsdoc: { mode: "typescript" } },
  },

  // ⚛️ React / Hooks / Accessibility
  // @eslint-react/eslint-plugin: native ESLint 10+ support, TypeScript-first.
  // recommended-typescript covers: no-missing-key, no-array-index-key,
  // no-nested-component-definitions, dom/no-unsafe-target-blank,
  // hooks-extra/rules-of-hooks, hooks-extra/exhaustive-deps, and more.
  {
    ...eslintReact.configs["recommended-typescript"],
    files: ["**/*.tsx", "**/*.jsx"],
  },
  {
    files: ["**/*.tsx", "**/*.jsx"],
    languageOptions: {
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    plugins: {
      "jsx-a11y": jsxA11yPlugin,
    },
    rules: {
      // Downgrade from the preset's default "error" to "warn"
      "@eslint-react/no-array-index-key": "warn",
      "perfectionist/sort-jsx-props": [
        "error",
        {
          customGroups: [
            { elementNamePattern: "^(key|ref)$", groupName: "reserved" },
            { groupName: "shorthand", modifiers: ["shorthand"] },
          ],
          groups: ["reserved", "unknown", "shorthand"],
          order: "asc",
          type: "natural",
        },
      ],

      // Accessibility rules
      ...jsxA11yPlugin.configs.recommended.rules,
    },
  },

  // 🧪 Test Files
  // Relaxed rules for test files: allow `any`, unsafe operations, and console
  {
    files: [
      "**/*.test.ts",
      "**/*.test.tsx",
      "**/testing/**/*.{ts,tsx,mts,cts,js,mjs,cjs,jsx}",
      "**/__tests__/**/*.{ts,tsx,mts,cts,js,mjs,cjs,jsx}",
    ],
    languageOptions: {
      globals: {
        ...vitestPlugin.environments.env.globals,
      },
    },
    plugins: {
      "@typescript-eslint": tseslint.plugin,
      vitest: vitestPlugin,
    },
    rules: {
      ...vitestPlugin.configs.recommended.rules,
      "@typescript-eslint/consistent-return": "off",
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-shadow": "off", // test scopes commonly shadow outer variables
      "@typescript-eslint/no-unsafe-assignment": "warn",
      "@typescript-eslint/no-unsafe-call": "warn",
      "@typescript-eslint/no-unsafe-member-access": "warn",
      "@typescript-eslint/no-unsafe-return": "warn",
      "@typescript-eslint/unbound-method": "off",
      "better-max-params/better-max-params": "off",
      complexity: "off",
      "max-classes-per-file": "off",
      "max-depth": "off",
      "max-lines": "off",
      "max-lines-per-function": "off",
      "max-nested-callbacks": "off",
      "max-params": "off",
      "max-statements": "off",
      "no-console": "off",
      "no-param-reassign": "off", // mocks commonly mutate parameters
      "vitest/consistent-each-for": [
        "error",
        {
          describe: "each",
          it: "each",
          suite: "each",
          test: "each",
        },
      ],
      "vitest/consistent-test-filename": "error",
      "vitest/consistent-test-it": "error",
      "vitest/consistent-vitest-vi": "error",
      "vitest/hoisted-apis-on-top": "error",
      "vitest/max-nested-describe": ["error", { max: 3 }],
      "vitest/no-alias-methods": "error",
      "vitest/no-commented-out-tests": "error",
      "vitest/no-disabled-tests": "error",
      "vitest/no-duplicate-hooks": "error",
      "vitest/no-focused-tests": "error",
      "vitest/no-identical-title": "error",
      "vitest/no-import-node-test": "error",
      "vitest/no-restricted-matchers": [
        "error",
        {
          toBeFalsy:
            "Use toBe(false) or a more specific matcher for clearer assertions.",
          toBeTruthy:
            "Use toBe(true) or a more specific matcher for clearer assertions.",
        },
      ],
      "vitest/no-standalone-expect": "error",
      "vitest/no-test-prefixes": "error",
      "vitest/no-test-return-statement": "error",
      "vitest/no-unneeded-async-expect-function": "error",
      "vitest/padding-around-after-all-blocks": "error",
      "vitest/padding-around-after-each-blocks": "error",
      "vitest/padding-around-all": "error",
      "vitest/padding-around-before-all-blocks": "error",
      "vitest/padding-around-before-each-blocks": "error",
      "vitest/padding-around-describe-blocks": "error",
      "vitest/padding-around-expect-groups": "error",
      "vitest/padding-around-test-blocks": "error",
      "vitest/prefer-called-exactly-once-with": "error",
      "vitest/prefer-called-times": "error",
      "vitest/prefer-called-with": "error",
      "vitest/prefer-comparison-matcher": "error",
      "vitest/prefer-describe-function-title": "error",
      "vitest/prefer-each": "error",
      "vitest/prefer-equality-matcher": "error",
      "vitest/prefer-expect-assertions": "off",
      "vitest/prefer-expect-resolves": "error",
      "vitest/prefer-hooks-in-order": "error",
      "vitest/prefer-hooks-on-top": "error",
      "vitest/prefer-importing-vitest-globals": "error",
      "vitest/prefer-lowercase-title": "error",
      "vitest/prefer-mock-promise-shorthand": "error",
      "vitest/prefer-mock-return-shorthand": "error",
      "vitest/prefer-strict-equal": "error",
      "vitest/prefer-to-be": "error",
      "vitest/prefer-to-contain": "error",
      "vitest/prefer-to-have-been-called-times": "error",
      "vitest/prefer-to-have-length": "error",
      "vitest/prefer-vi-mocked": "error",
      "vitest/require-awaited-expect-poll": "error",
      "vitest/require-mock-type-parameters": [
        "warn",
        { checkImportFunctions: false },
      ],
      "vitest/require-to-throw-message": "error",
      "vitest/require-top-level-describe": [
        "error",
        { maxNumberOfTopLevelDescribes: 1 },
      ],
      "vitest/unbound-method": "error",
      "vitest/valid-describe-callback": "error",
      "vitest/valid-expect": "error",
      "vitest/valid-expect-in-promise": "error",
    },
    settings: {
      vitest: {
        typecheck: true,
      },
    },
  },

  // 🧪 Test Setup Files
  // Setup/mocks files execute global hooks via Vitest setupFiles and are not test suites.
  {
    files: ["**/testing/setup.ts", "**/testing/mocks.ts"],
    rules: {
      "vitest/require-top-level-describe": "off",
    },
  },

  // 📜 Scripts Folder
  // Allow console statements in scripts — these are CLI utilities, not application code
  {
    files: ["scripts/**/*.{ts,mts,cts,js,mjs,cjs}"],
    rules: {
      "no-console": "off",
    },
  },

  // 🟨 JavaScript Config Files
  // Disables ALL type-checked rules for .js/.mjs/.cjs files since they
  // lack TypeScript type information (e.g., *.config.cjs, commitlint.config.ts)
  {
    files: ["**/*.js", "**/*.mjs", "**/*.cjs"],
    plugins: {
      "@typescript-eslint": tseslint.plugin,
    },
    rules: {
      "@typescript-eslint/no-require-imports": "off",
      // Disable ALL type-checked rules for JS files
      "@typescript-eslint/await-thenable": "off",
      "@typescript-eslint/consistent-return": "off",
      "@typescript-eslint/consistent-type-exports": "off",
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "@typescript-eslint/naming-convention": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/no-floating-promises": "off",
      "@typescript-eslint/no-meaningless-void-operator": "off",
      "@typescript-eslint/no-misused-promises": "off",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": "off",
      "@typescript-eslint/no-unnecessary-condition": "off",
      "@typescript-eslint/no-unnecessary-type-assertion": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-useless-constructor": "off",
      "@typescript-eslint/only-throw-error": "off",
      "@typescript-eslint/prefer-optional-chain": "off",
      "@typescript-eslint/prefer-readonly": "off",
      "@typescript-eslint/prefer-reduce-type-parameter": "off",
      "@typescript-eslint/prefer-return-this-type": "off",
      "@typescript-eslint/promise-function-async": "off",
      "@typescript-eslint/require-await": "off",
      "@typescript-eslint/switch-exhaustiveness-check": "off",
    },
  },

  // 📦 JSON Files
  // JSON/JSONC/JSON5 linting with style enforcement and Nx dependency checks
  ...jsoncPlugin.configs["flat/recommended-with-jsonc"].map((config) => ({
    ...config,
    files: ["**/*.json", "**/*.jsonc", "**/*.jsonl", "**/*.json5"],
  })),
  {
    files: ["**/*.json", "**/*.jsonc", "**/*.jsonl", "**/*.json5"],
    ignores: ["projectStructure.cache.json"],
    rules: {
      // Keep Nx dependency checks enabled
      "@nx/dependency-checks": [
        "error",
        {
          ignoredDependencies: ["@codebase/logging"],
        },
      ],
      // JSONC style rules
      "jsonc/comma-dangle": ["error", "never"],
      "jsonc/indent": ["error", 2],
      "jsonc/quotes": ["error", "double"],
      "jsonc/sort-array-values": [
        "error",
        {
          minValues: 2,
          order: { caseSensitive: false, natural: true, type: "asc" },
          pathPattern: String.raw`^(?!(?:.*\.)?commands?$)`,
        },
      ],
      // Exempt the `exports` subtree from sorting so package condition order
      // (e.g., `types` before `default`) can be manually controlled for correct
      // TypeScript declaration resolution without being sorted alphabetically.
      "jsonc/sort-keys": [
        "error",
        {
          minKeys: 2,
          order: { caseSensitive: false, natural: false, type: "asc" },
          pathPattern: String.raw`^(?!(?:.*\.)?exports(?:[\[.].*)?$)`,
        },
      ],
    },
  },

  // 🧭 tsconfig.json path aliases
  // Local modules are imported with relative paths; path aliases are reserved
  // for cross-project mappings. A self-referential alias (one pointing back
  // into the project's own directory) adds indirection, hides dependency
  // cycles from dependency-cruiser, and breaks when files move.
  //
  // Deliberately NOT flagged:
  // - `./node_modules/...` entries, which are type shims for real packages
  // - `../`-style entries, which are the cross-project mappings we want
  // - non-`@`/`~` keys such as `codebase/configuration/*`
  {
    files: ["**/tsconfig.json", "tsconfig.json"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          message:
            "Self-referential tsconfig path alias. Import local files with a relative path instead; reserve path aliases for cross-project mappings.",
          selector:
            "JSONProperty[key.value=/^[@~]/] > JSONArrayExpression > JSONLiteral[value=/^\\.\\//]:not([value=/node_modules/])",
        },
      ],
    },
  },

  // 📦 JSONC Files
  // JSONC files support trailing commas; align with Prettier's trailingComma: "all" + jsonc parser
  {
    files: ["**/*.jsonc"],
    rules: {
      "jsonc/comma-dangle": ["error", "always-multiline"],
    },
  },

  // 🐳 devcontainer.json files
  // Allow line-separated groups in devcontainer.json for security audit tool flexibility
  {
    files: ["**/devcontainer.json"],
    rules: {
      "jsonc/sort-array-values": [
        "error",
        {
          minValues: 2,
          order: { caseSensitive: false, natural: true, type: "asc" },
          pathPattern: "^(?!runArgs$)",
        },
      ],
    },
  },

  // 🕸️ codependix graph JSON files
  // Emitted from the Nx project graph, a NestJS container, or a `ts.Program`,
  // in whichever order each source discovers its projects, modules, or
  // files — not alphabetical. Enforcing array order here would make every
  // `codependix map --write` immediately fail its own `--check`, the same
  // reformatting-vs-drift conflict `configuration/.oxfmtignore` already
  // solves for `oxfmt` and `.conformetry/**`.
  {
    files: ["**/codependix-*graph.json"],
    rules: {
      "jsonc/sort-array-values": "off",
    },
  },

  // 📋 YAML Files
  // YAML/YML linting with indent, quoting, and best practice rules
  ...eslintPluginYml.configs["flat/standard"].map((config) => ({
    ...config,
    files: ["**/*.yaml", "**/*.yml"],
  })),
  ...eslintPluginYml.configs["flat/prettier"].map((config) => ({
    ...config,
    files: ["**/*.yaml", "**/*.yml"],
  })),
  {
    files: ["**/*.yaml", "**/*.yml"],
    rules: {
      // Style rules
      "yml/indent": ["error", 2],
      "yml/key-spacing": ["error", { afterColon: true, beforeColon: false }],
      "yml/no-multiple-empty-lines": [
        "error",
        { max: 1, maxBOF: 0, maxEOF: 0 },
      ],
      "yml/quotes": ["error", { avoidEscape: false, prefer: "double" }],
      "yml/spaced-comment": ["error", "always"],

      // Best practices
      "yml/no-empty-document": "error",
      "yml/no-empty-key": "error",
      "yml/no-empty-mapping-value": "off", // Allow empty values (common in GitHub Actions triggers)
      "yml/no-empty-sequence-entry": "error",
      "yml/no-tab-indent": "error",
      "yml/plain-scalar": ["error", "always"],

      // Disable sorting by default (can be enabled per-project)
      "yml/sort-keys": "off",
      "yml/sort-sequence-values": "off",
    },
  },

  // ⚙️ Config File Overrides
  // Tooling config files use relative paths to import shared workspace config
  // (e.g., eslint.config.ts, tailwind.config.cjs extending root config files).
  // They cannot use npm scope resolution because the shared config files are not
  // publishable packages — they live in configuration/ at the workspace root.
  {
    files: [
      "**/*.config.ts",
      "**/*.config.js",
      "**/*.config.mjs",
      "**/*.config.cjs",
    ],
    rules: {
      "@nx/enforce-module-boundaries": "off",
      "import/no-relative-packages": "off",
      "import/no-relative-parent-imports": "off",
      // Config files often contain large inline object/array definitions
      "max-classes-per-file": "off",
      "max-lines": "off",
      "max-lines-per-function": "off",
    },
  },

  // 🔬 Vitest Config Files
  // Disable type-checked rules for vitest configs (circular dependency issues)
  {
    files: ["**/vitest.config.ts", "**/vitest.config.base.ts"],
    plugins: {
      "@typescript-eslint": tseslint.plugin,
    },
    rules: {
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
    },
  },

  // 🔧 Self-Config
  // Relaxed rules for eslint.config.ts itself (plugin typing limitations)
  {
    files: ["configuration/eslint.config.ts"],
    plugins: {
      "@typescript-eslint": tseslint.plugin,
    },
    rules: {
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": "off",
      "@typescript-eslint/no-unnecessary-condition": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
    },
  },

  // 📝 Markdown Placement
  // Establishes markdown as markdown, and judges where every markdown file
  // sits. This is separate from the authored-content rules below so that it
  // reaches generated pages too: the same `folder-structure` rule the rest of
  // the workspace is judged by, reading the same `codebase-structure.json`,
  // bound to mdast's root node. Without it an undeclared markdown file — or a
  // whole directory of them — passes lint, which is how `openwiki/` stayed
  // undeclared.
  {
    files: ["**/*.md"],
    language: "markdown/gfm",
    languageOptions: {
      frontmatter: "yaml",
    },
    plugins: {
      // Registered here rather than only below, because `language:
      // "markdown/gfm"` resolves against the plugins of the config this file
      // ends up with — and a generated page excluded from the rules below
      // would otherwise fail with `Could not find "gfm" in plugin "markdown"`.
      markdown,
      "markdown-structure": markdownStructurePlugin,
    },
    rules: {
      "markdown-structure/folder-structure": "error",
    },
  },

  // 📝 Markdown Files
  // GitHub Flavored Markdown (GFM) content rules, for the markdown this
  // repository writes. `openwiki/` is excluded because its pages are generated
  // and must not be hand-edited — its generator emits several H1s per page —
  // which is the same reason `markdownlint` and `cspell` exclude the vendored
  // skills. Placement above is judged for those pages regardless.
  {
    files: ["**/*.md"],
    ignores: [".agents/**", "openwiki/**"],
    rules: {
      // Enable markdown-specific rules
      "markdown/fenced-code-language": "warn",
      "markdown/heading-increment": "error",
      "markdown/no-bare-urls": "off",
      "markdown/no-duplicate-definitions": "error",
      "markdown/no-duplicate-headings": "warn",
      "markdown/no-empty-definitions": "error",
      "markdown/no-empty-images": "error",
      "markdown/no-empty-links": "error",
      // `details`/`summary` is the one disclosure GitHub renders and markdown
      // cannot express, and generated sections long enough to need it — the
      // callidescope call stacks — are exactly where it earns its place.
      // `strong` is allowed because `**bold**` markdown is never reprocessed
      // inside a `<summary>` on the same line as its opening `<details>` tag
      // (CommonMark treats them as one raw HTML block), so `<strong>` is the
      // only way to bold a summary's text. `markdownlint`'s MD033 already
      // permits inline HTML here.
      "markdown/no-html": [
        "error",
        { allowed: ["a", "details", "img", "strong", "summary"] },
      ],
      "markdown/no-invalid-label-refs": "error",
      "markdown/no-missing-atx-heading-space": "error",
      "markdown/no-missing-label-refs": "error",
      "markdown/no-missing-link-fragments": "error",
      "markdown/no-multiple-h1": "error",
      "markdown/no-reference-like-urls": "error",
      "markdown/no-reversed-media-syntax": "error",
      "markdown/no-space-in-emphasis": "error",
      "markdown/no-unused-definitions": "error",
      "markdown/require-alt-text": "error",
      "markdown/table-column-count": "error",
    },
  },

  // 💅 Prettier (must be last)
  // Disables all formatting rules that conflict with Prettier
  eslintConfigPrettier,
  {
    // Re-enable rules disabled by eslint-config-prettier that we still want enforced
    rules: {
      "@typescript-eslint/naming-convention": "off",
      "no-multiple-empty-lines": ["warn", { max: 2, maxBOF: 0, maxEOF: 1 }],
    },
  },
] as ConfigWithExtends[];
