import { defineConfig } from "oxlint";

export default defineConfig({
  // Oxlint — Fast primary linter (~50–100× faster than ESLint)
  // https://oxc.rs/docs/guide/usage/linter/config

  // Oxlint is the authoritative linter for rules it supports. ESLint is
  // supplementary — it covers TypeScript-specific rules, import ordering,
  // JSX a11y, Markdown, YAML, and JSON linting that Oxlint cannot handle.
  // Both tools run independently as separate Nx targets; both must pass.
  // Duplicate diagnostics on overlapping rules are accepted by design
  // (`eslint-plugin-oxlint` was evaluated and removed — see planning doc).

  // This config was auto-generated by @oxlint/migrate from eslint.config.ts
  // (270 rules mapped, 156 skipped as unsupported by Oxlint), then manually
  // refined. Each override block maps to an ESLint config section.

  // Related configs:
  //   - eslint.config.ts — supplementary linter (TypeScript, imports, a11y, etc.)
  //   - oxfmt.config.ts — primary formatter
  //   - prettier.config.ts — supplementary formatter

  // Nx targets:
  //   - `oxlint` (read-only): `oxlint {projectRoot}/src`
  //   - `oxlint` with `--fix` flag: auto-fixes where possible

  // Categories
  // All categories off — rules are configured explicitly in the overrides
  // array below. This prevents Oxlint's built-in rule sets from enabling
  // rules we haven't explicitly opted into via @oxlint/migrate.
  categories: {
    correctness: "off",
    nursery: "off",
    pedantic: "off",
    restriction: "off",
    style: "off",
    suspicious: "off",
  },
  // 🌐 Environments
  // Declares which global variables are available (prevents no-undef errors).
  // Matches the ESLint env settings for this codebase's runtime targets.
  env: {
    // Browser globals for lexico (web app) and components-web
    browser: true,
    builtin: true,
    commonjs: true,
    es2020: true,
    // Node globals for caelundas (CLI), build scripts, and config files
    node: true,
  },

  // Overrides — auto-generated by @oxlint/migrate from eslint.config.ts

  // 270 ESLint rules were mapped to Oxlint equivalents; 156 were skipped
  // (unsupported). Each override block targets specific file types and maps
  // to a corresponding section of the ESLint flat config.

  // Override index:
  //   [0]  ESLint recommended — base rules for ALL files (TS/JS/JSON/YAML)
  //   [1]  ESLint recommended + TS — TypeScript-specific base rules
  //   [2]  ESLint recommended + TS (JS) — same rules adapted for JS files
  //   [3]  Unicorn plugin — modern JS best practices (TS + JS)
  //   [4]  Test file relaxations — looser unicorn rules in tests
  //   [5]  JS config file relaxations — allow CommonJS in config files

  //   [6]  Strict project rules — import, type-safety, and code quality
  //   [7]  TS strict + stylistic — TypeScript-specific strict/style rules
  //   [8]  React/JSX/a11y — React component and accessibility rules
  //   [9]  Test relaxations (TS) — allow `any` and console in tests
  //   [10] JS relaxations (TS) — disable TS-only rules for JS files
  //   [11] JSON rules — disable inapplicable rules for JSON files
  //   [12] YAML rules — disable inapplicable rules for YAML files
  //
  overrides: [
    // ✅ [0] ESLint recommended — base rules for all file types
    // Maps to: eslint.configs.recommended (eslint.config.ts)
    // Covers fundamental correctness rules (no-debugger, no-unused-vars, etc.)
    // that apply universally across TS, JS, JSON, and YAML files.
    {
      files: [
        "**/*.cjs",
        "**/*.cts",
        "**/*.js",
        "**/*.json",
        "**/*.json5",
        "**/*.jsonc",
        "**/*.jsx",
        "**/*.mjs",
        "**/*.mts",
        "**/*.ts",
        "**/*.tsx",
        "**/*.yaml",
        "**/*.yml",
      ],
      rules: {
        "constructor-super": "error",
        "for-direction": "error",
        "no-async-promise-executor": "error",
        "no-case-declarations": "error",
        "no-class-assign": "error",
        "no-compare-neg-zero": "error",
        "no-cond-assign": "error",
        "no-const-assign": "error",
        "no-constant-binary-expression": "error",
        "no-constant-condition": "error",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-delete-var": "error",
        "no-dupe-class-members": "error",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-empty": "error",
        "no-empty-character-class": "error",
        "no-empty-pattern": "error",
        "no-empty-static-block": "error",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "error",
        "no-fallthrough": "error",
        "no-func-assign": "error",
        "no-global-assign": "error",
        "no-import-assign": "error",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-loss-of-precision": "error",
        "no-misleading-character-class": "error",
        "no-new-native-nonconstructor": "error",
        "no-nonoctal-decimal-escape": "error",
        "no-obj-calls": "error",
        "no-prototype-builtins": "error",
        "no-redeclare": "error",
        "no-regex-spaces": "error",
        "no-self-assign": "error",
        "no-setter-return": "error",
        "no-shadow-restricted-names": "error",
        "no-sparse-arrays": "error",
        "no-this-before-super": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "error",
        "no-unsafe-optional-chaining": "error",
        "no-unused-labels": "error",
        "no-unused-private-class-members": "error",
        "no-unused-vars": "error",
        "no-useless-backreference": "error",
        "no-useless-catch": "error",
        "no-useless-escape": "error",
        "no-with": "error",
        "require-yield": "error",
        "use-isnan": "error",
        "valid-typeof": "error",
      },
    },
    // 🔷 [1] ESLint recommended + TS — TypeScript-specific overrides
    // Maps to: tseslint.configs.recommended (eslint.config.ts)
    // Inherits base recommended rules but turns OFF rules that TypeScript's
    // compiler already handles (e.g., constructor-super, no-dupe-keys).
    // Adds @typescript-eslint rules for TS-specific correctness.
    // Some rules set to "warn" here are escalated to "error" in override [7].
    {
      files: ["**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx"],
      plugins: ["typescript"],
      rules: {
        "@typescript-eslint/adjacent-overload-signatures": "error",
        // @typescript-eslint recommended rules
        "@typescript-eslint/ban-ts-comment": "error",
        "@typescript-eslint/explicit-function-return-type": "off",
        // These are OFF here but ENABLED in override [7] (strict/stylistic)
        "@typescript-eslint/explicit-module-boundary-types": "off",
        "@typescript-eslint/no-duplicate-enum-values": "error",
        "@typescript-eslint/no-empty-interface": "error",
        "@typescript-eslint/no-empty-object-type": "error",
        "@typescript-eslint/no-explicit-any": "warn",
        "@typescript-eslint/no-extra-non-null-assertion": "error",
        "@typescript-eslint/no-inferrable-types": "error",
        "@typescript-eslint/no-misused-new": "error",
        "@typescript-eslint/no-namespace": "error",
        "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
        "@typescript-eslint/no-non-null-assertion": "warn",
        "@typescript-eslint/no-require-imports": "off",
        "@typescript-eslint/no-this-alias": "error",
        "@typescript-eslint/no-unnecessary-type-constraint": "error",
        "@typescript-eslint/no-unsafe-declaration-merging": "error",
        "@typescript-eslint/no-unsafe-function-type": "error",
        "@typescript-eslint/no-wrapper-object-types": "error",
        "@typescript-eslint/prefer-as-const": "error",
        "@typescript-eslint/prefer-namespace-keyword": "error",
        "@typescript-eslint/triple-slash-reference": "error",
        // Rules turned OFF — TypeScript compiler handles these natively
        "constructor-super": "off",
        // Rules kept from base recommended
        "for-direction": "error",
        "no-array-constructor": "error",
        "no-async-promise-executor": "error",
        "no-case-declarations": "error",
        "no-class-assign": "off",
        "no-compare-neg-zero": "error",
        "no-cond-assign": "error",
        "no-const-assign": "off",
        "no-constant-binary-expression": "error",
        "no-constant-condition": "error",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-delete-var": "error",
        "no-dupe-class-members": "off",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "off",
        "no-duplicate-case": "error",
        "no-empty": "error",
        "no-empty-character-class": "error",
        "no-empty-function": "error",
        "no-empty-pattern": "error",
        "no-empty-static-block": "error",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "error",
        "no-fallthrough": "error",
        "no-func-assign": "off",
        "no-global-assign": "error",
        "no-import-assign": "off",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-loss-of-precision": "error",
        "no-misleading-character-class": "error",
        "no-new-native-nonconstructor": "off",
        "no-nonoctal-decimal-escape": "error",
        "no-obj-calls": "off",
        "no-prototype-builtins": "error",
        "no-redeclare": "off",
        "no-regex-spaces": "error",
        "no-self-assign": "error",
        "no-setter-return": "off",
        "no-shadow-restricted-names": "error",
        "no-sparse-arrays": "error",
        "no-this-before-super": "off",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "off",
        "no-unsafe-optional-chaining": "error",
        "no-unused-expressions": "error",
        "no-unused-labels": "error",
        "no-unused-private-class-members": "error",
        "no-unused-vars": "warn",
        "no-useless-backreference": "error",
        "no-useless-catch": "error",
        "no-useless-escape": "error",
        // ES6+ rules
        "no-var": "error",
        "no-with": "off",
        "prefer-const": "error",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
        "require-yield": "error",
        "use-isnan": "error",
        "valid-typeof": "error",
      },
    },
    // 🔶 [2] ESLint recommended + TS (JS files)
    // Maps to: tseslint.configs.recommended for JS files
    // Same pattern as override [1] but for JavaScript files. Includes TS
    // plugin rules because ESLint's TS plugin still validates JS files
    // (e.g., JSDoc type annotations, import syntax).
    {
      files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs"],
      plugins: ["typescript"],
      rules: {
        "@typescript-eslint/adjacent-overload-signatures": "error",
        "@typescript-eslint/ban-ts-comment": "error",
        "@typescript-eslint/explicit-function-return-type": "off",
        "@typescript-eslint/explicit-module-boundary-types": "off",
        "@typescript-eslint/no-duplicate-enum-values": "error",
        "@typescript-eslint/no-empty-interface": "error",
        "@typescript-eslint/no-empty-object-type": "error",
        "@typescript-eslint/no-explicit-any": "warn",
        "@typescript-eslint/no-extra-non-null-assertion": "error",
        "@typescript-eslint/no-inferrable-types": "error",
        "@typescript-eslint/no-misused-new": "error",
        "@typescript-eslint/no-namespace": "error",
        "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
        "@typescript-eslint/no-non-null-assertion": "warn",
        "@typescript-eslint/no-require-imports": "off",
        "@typescript-eslint/no-this-alias": "error",
        "@typescript-eslint/no-unnecessary-type-constraint": "error",
        "@typescript-eslint/no-unsafe-declaration-merging": "error",
        "@typescript-eslint/no-unsafe-function-type": "error",
        "@typescript-eslint/no-var-requires": "off",
        "@typescript-eslint/no-wrapper-object-types": "error",
        "@typescript-eslint/prefer-as-const": "error",
        "@typescript-eslint/prefer-namespace-keyword": "error",
        "@typescript-eslint/triple-slash-reference": "error",
        "constructor-super": "off",
        "for-direction": "error",
        "no-array-constructor": "error",
        "no-async-promise-executor": "error",
        "no-case-declarations": "error",
        "no-class-assign": "off",
        "no-compare-neg-zero": "error",
        "no-cond-assign": "error",
        "no-const-assign": "off",
        "no-constant-binary-expression": "error",
        "no-constant-condition": "error",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-delete-var": "error",
        "no-dupe-class-members": "off",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "off",
        "no-duplicate-case": "error",
        "no-empty": "error",
        "no-empty-character-class": "error",
        "no-empty-function": "error",
        "no-empty-pattern": "error",
        "no-empty-static-block": "error",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "error",
        "no-fallthrough": "error",
        "no-func-assign": "off",
        "no-global-assign": "error",
        "no-import-assign": "off",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-loss-of-precision": "error",
        "no-misleading-character-class": "error",
        "no-new-native-nonconstructor": "off",
        "no-nonoctal-decimal-escape": "error",
        "no-obj-calls": "off",
        "no-prototype-builtins": "error",
        "no-redeclare": "off",
        "no-regex-spaces": "error",
        "no-self-assign": "error",
        "no-setter-return": "off",
        "no-shadow-restricted-names": "error",
        "no-sparse-arrays": "error",
        "no-this-before-super": "off",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "off",
        "no-unsafe-optional-chaining": "error",
        "no-unused-expressions": "error",
        "no-unused-labels": "error",
        "no-unused-private-class-members": "error",
        "no-unused-vars": "warn",
        "no-useless-backreference": "error",
        "no-useless-catch": "error",
        "no-useless-escape": "error",
        "no-var": "error",
        "no-with": "off",
        "prefer-const": "error",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
        "require-yield": "error",
        "use-isnan": "error",
        "valid-typeof": "error",
      },
    },
    // 🦄 [3] Unicorn plugin — modern JavaScript best practices
    // Maps to: eslint-plugin-unicorn/recommended in eslint.config.ts
    // Enforces modern JS patterns: prefer-at, prefer-includes, etc.
    //
    // Disabled rules (matching ESLint config):
    //   - filename-case: off — PascalCase React components conflict
    //   - no-array-for-each: off — forEach is idiomatic in this codebase
    //   - no-array-reduce: off — reduce is used in data transformations
    //   - no-null: off — Supabase/React APIs return null
    //   - no-process-exit: off — caelundas CLI uses process.exit
    //   - prefer-module: off — CommonJS config files (*.cjs)
    //   - prefer-top-level-await: off — not all entry points support TLA
    //   - consistent-function-scoping: off — React render helpers pattern
    {
      env: {
        es2026: true,
      },
      files: [
        "**/*.cjs",
        "**/*.cts",
        "**/*.js",
        "**/*.jsx",
        "**/*.mjs",
        "**/*.mts",
        "**/*.ts",
        "**/*.tsx",
      ],
      rules: {
        // Disabled to allow unicorn/no-negated-condition to take precedence
        "no-negated-condition": "off",
        "no-nested-ternary": "off",
        "unicorn/catch-error-name": "error",
        "unicorn/consistent-assert": "error",
        "unicorn/consistent-date-clone": "error",
        "unicorn/consistent-empty-array-spread": "error",
        "unicorn/consistent-existence-index-check": "error",
        "unicorn/consistent-function-scoping": "off",
        "unicorn/error-message": "error",
        "unicorn/escape-case": "error",
        "unicorn/explicit-length-check": "error",
        "unicorn/filename-case": "off",
        "unicorn/new-for-builtins": "error",
        "unicorn/no-abusive-eslint-disable": "error",
        "unicorn/no-accessor-recursion": "error",
        "unicorn/no-anonymous-default-export": "error",
        "unicorn/no-array-callback-reference": "error",
        "unicorn/no-array-for-each": "off",
        "unicorn/no-array-method-this-argument": "error",
        "unicorn/no-array-reduce": "off",
        "unicorn/no-array-reverse": "error",
        "unicorn/no-array-sort": "error",
        "unicorn/no-await-expression-member": "error",
        "unicorn/no-await-in-promise-methods": "error",
        "unicorn/no-console-spaces": "error",
        "unicorn/no-document-cookie": "error",
        "unicorn/no-empty-file": "off",
        "unicorn/no-hex-escape": "error",
        "unicorn/no-immediate-mutation": "error",
        "unicorn/no-instanceof-builtins": "error",
        "unicorn/no-invalid-fetch-options": "error",
        "unicorn/no-invalid-remove-event-listener": "error",
        "unicorn/no-lonely-if": "error",
        "unicorn/no-magic-array-flat-depth": "error",
        "unicorn/no-negated-condition": "error",
        "unicorn/no-negation-in-equality-check": "error",
        "unicorn/no-new-array": "error",
        "unicorn/no-new-buffer": "error",
        "unicorn/no-null": "off",
        "unicorn/no-object-as-default-parameter": "error",
        "unicorn/no-process-exit": "off",
        "unicorn/no-single-promise-in-promise-methods": "error",
        "unicorn/no-static-only-class": "error",
        "unicorn/no-thenable": "error",
        "unicorn/no-this-assignment": "error",
        "unicorn/no-typeof-undefined": "error",
        "unicorn/no-unnecessary-array-flat-depth": "error",
        "unicorn/no-unnecessary-array-splice-count": "error",
        "unicorn/no-unnecessary-await": "error",
        "unicorn/no-unnecessary-slice-end": "error",
        "unicorn/no-unreadable-array-destructuring": "error",
        "unicorn/no-unreadable-iife": "error",
        "unicorn/no-useless-collection-argument": "error",
        "unicorn/no-useless-error-capture-stack-trace": "error",
        "unicorn/no-useless-fallback-in-spread": "error",
        "unicorn/no-useless-length-check": "error",
        "unicorn/no-useless-promise-resolve-reject": "error",
        "unicorn/no-useless-spread": "error",
        "unicorn/no-useless-switch-case": "error",
        "unicorn/no-useless-undefined": "error",
        "unicorn/no-zero-fractions": "error",
        "unicorn/numeric-separators-style": "off",
        "unicorn/prefer-add-event-listener": "error",
        "unicorn/prefer-array-find": "error",
        "unicorn/prefer-array-flat": "error",
        "unicorn/prefer-array-flat-map": "error",
        "unicorn/prefer-array-index-of": "error",
        "unicorn/prefer-array-some": "error",
        "unicorn/prefer-at": "error",
        "unicorn/prefer-bigint-literals": "error",
        "unicorn/prefer-blob-reading-methods": "error",
        "unicorn/prefer-class-fields": "error",
        "unicorn/prefer-classlist-toggle": "error",
        "unicorn/prefer-code-point": "error",
        "unicorn/prefer-date-now": "error",
        "unicorn/prefer-default-parameters": "error",
        "unicorn/prefer-dom-node-append": "error",
        "unicorn/prefer-dom-node-dataset": "error",
        "unicorn/prefer-dom-node-remove": "error",
        "unicorn/prefer-dom-node-text-content": "error",
        "unicorn/prefer-event-target": "error",
        "unicorn/prefer-global-this": "error",
        "unicorn/prefer-includes": "error",
        "unicorn/prefer-keyboard-event-key": "error",
        "unicorn/prefer-logical-operator-over-ternary": "error",
        "unicorn/prefer-math-min-max": "error",
        "unicorn/prefer-math-trunc": "error",
        "unicorn/prefer-modern-dom-apis": "error",
        "unicorn/prefer-modern-math-apis": "error",
        "unicorn/prefer-module": "off",
        "unicorn/prefer-native-coercion-functions": "error",
        "unicorn/prefer-negative-index": "error",
        "unicorn/prefer-node-protocol": "error",
        "unicorn/prefer-number-properties": "error",
        "unicorn/prefer-object-from-entries": "error",
        "unicorn/prefer-optional-catch-binding": "error",
        "unicorn/prefer-prototype-methods": "error",
        "unicorn/prefer-query-selector": "error",
        "unicorn/prefer-reflect-apply": "error",
        "unicorn/prefer-regexp-test": "error",
        "unicorn/prefer-response-static-json": "error",
        "unicorn/prefer-set-has": "error",
        "unicorn/prefer-set-size": "error",
        "unicorn/prefer-spread": "error",
        "unicorn/prefer-string-raw": "error",
        "unicorn/prefer-string-replace-all": "error",
        "unicorn/prefer-string-slice": "error",
        "unicorn/prefer-string-starts-ends-with": "error",
        "unicorn/prefer-string-trim-start-end": "error",
        "unicorn/prefer-structured-clone": "error",
        "unicorn/prefer-ternary": "error",
        "unicorn/prefer-top-level-await": "off",
        "unicorn/prefer-type-error": "error",
        "unicorn/relative-url-style": "error",
        "unicorn/require-array-join-separator": "error",
        "unicorn/require-module-attributes": "error",
        "unicorn/require-module-specifiers": "error",
        "unicorn/require-number-to-fixed-digits-argument": "error",
        "unicorn/require-post-message-target-origin": "off",
        "unicorn/switch-case-braces": "error",
        "unicorn/text-encoding-identifier-case": "error",
        "unicorn/throw-new-error": "error",
      },
    },
    // 🧪 [4] Test file relaxations (unicorn)
    // Tests often need factory functions and explicit undefined assertions
    {
      files: ["**/*.spec.ts", "**/*.test.ts", "**/testing/**"],
      rules: {
        "unicorn/consistent-function-scoping": "off",
        "unicorn/no-useless-undefined": "off",
      },
    },
    // ⚙️ [5] JS/config file relaxations
    // CommonJS config files (eslint.config.js, *.cjs) can't use ES modules
    {
      files: ["**/*.cjs", "**/*.js", "**/*.mjs"],
      rules: {
        "unicorn/prefer-module": "off",
      },
    },
    // 🔒 [6] Strict project rules — imports, type-safety, code quality
    // Maps to: the custom strict rules block in eslint.config.ts
    // These are the codebase's opinionated rules beyond "recommended":
    //   - Explicit return types required (allowExpressions, allowHOF)
    //   - Type imports enforced (consistent-type-imports with inline style)
    //   - No duplicate imports (use single import statement per module)
    //   - Unused vars with _ prefix pattern for intentional ignoring
    {
      files: [
        "**/*.cjs",
        "**/*.cts",
        "**/*.js",
        "**/*.jsx",
        "**/*.mjs",
        "**/*.mts",
        "**/*.ts",
        "**/*.tsx",
      ],
      plugins: ["import", "typescript"],
      rules: {
        // Disabled: ESLint's type-aware version handles this accurately for
        // decorator-metadata patterns (NestJS emitDecoratorMetadata). Oxlint
        // does not understand that constructor parameter types are value uses.
        "@typescript-eslint/consistent-type-imports": "off",
        "@typescript-eslint/explicit-function-return-type": [
          "error",
          {
            allowExpressions: true,
            allowHigherOrderFunctions: true,
            allowTypedFunctionExpressions: true,
          },
        ],
        "@typescript-eslint/explicit-module-boundary-types": "error",
        "@typescript-eslint/no-explicit-any": "error",
        "@typescript-eslint/no-import-type-side-effects": "error",
        eqeqeq: ["error", "always"],
        "import/default": "off",
        "import/namespace": "off",
        "import/no-duplicates": "error",
        "import/no-named-as-default-member": "off",
        "no-alert": "error",
        "no-debugger": "error",
        "no-duplicate-imports": "off",
        "no-throw-literal": "off",
        "no-unused-expressions": "error",
        "no-unused-vars": [
          "error",
          {
            argsIgnorePattern: "^_",
            caughtErrorsIgnorePattern: "^_",
            varsIgnorePattern: "^_",
          },
        ],
        "no-var": "error",
        "prefer-const": "error",
        "prefer-template": "error",
      },
    },
    // 🎨 [7] TypeScript strict + stylistic rules
    // Maps to: tseslint.configs.strict + tseslint.configs.stylistic
    // Escalates several rules from "warn" (in override [1]) to "error".
    // Adds strict rules: no-dynamic-delete, no-extraneous-class, etc.
    // Adds stylistic rules: array-type, consistent-type-definitions, etc.
    {
      files: ["**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx"],
      plugins: ["typescript"],
      rules: {
        "@typescript-eslint/adjacent-overload-signatures": "error",
        "@typescript-eslint/array-type": "error",
        // Stricter ban-ts-comment — require 10+ character justification
        "@typescript-eslint/ban-ts-comment": [
          "error",
          {
            minimumDescriptionLength: 10,
          },
        ],
        "@typescript-eslint/ban-tslint-comment": "error",
        "@typescript-eslint/class-literal-property-style": "error",
        "@typescript-eslint/consistent-generic-constructors": "error",
        "@typescript-eslint/consistent-indexed-object-style": "error",
        "@typescript-eslint/consistent-type-assertions": "error",
        "@typescript-eslint/consistent-type-definitions": "error",
        "@typescript-eslint/no-confusing-non-null-assertion": "error",
        "@typescript-eslint/no-duplicate-enum-values": "error",
        "@typescript-eslint/no-dynamic-delete": "error",
        "@typescript-eslint/no-empty-object-type": "error",
        "@typescript-eslint/no-explicit-any": "error",
        "@typescript-eslint/no-extra-non-null-assertion": "error",
        "@typescript-eslint/no-extraneous-class": [
          "error",
          { allowWithDecorator: true },
        ],
        "@typescript-eslint/no-inferrable-types": "error",
        "@typescript-eslint/no-invalid-void-type": "error",
        "@typescript-eslint/no-misused-new": "error",
        "@typescript-eslint/no-namespace": "error",
        "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
        "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
        "@typescript-eslint/no-non-null-assertion": "error",
        "@typescript-eslint/no-require-imports": "error",
        "@typescript-eslint/no-this-alias": "error",
        "@typescript-eslint/no-unnecessary-type-constraint": "error",
        "@typescript-eslint/no-unsafe-declaration-merging": "error",
        "@typescript-eslint/no-unsafe-function-type": "error",
        "@typescript-eslint/no-wrapper-object-types": "error",
        "@typescript-eslint/prefer-as-const": "error",
        "@typescript-eslint/prefer-for-of": "error",
        "@typescript-eslint/prefer-function-type": "error",
        "@typescript-eslint/prefer-literal-enum-member": "error",
        "@typescript-eslint/prefer-namespace-keyword": "error",
        "@typescript-eslint/triple-slash-reference": "error",
        "@typescript-eslint/unified-signatures": "error",
        // TypeScript compiler handles these — turned off
        "constructor-super": "off",
        "no-array-constructor": "error",
        "no-class-assign": "off",
        "no-const-assign": "off",
        "no-dupe-class-members": "off",
        "no-dupe-keys": "off",
        "no-empty-function": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-new-native-nonconstructor": "off",
        "no-obj-calls": "off",
        "no-redeclare": "off",
        "no-setter-return": "off",
        "no-this-before-super": "off",
        "no-throw-literal": "off",
        "no-unsafe-negation": "off",
        "no-unused-expressions": "error",
        "no-unused-vars": "error",
        "no-useless-constructor": "off",
        "no-var": "error",
        "no-with": "off",
        "prefer-const": "error",
        "prefer-promise-reject-errors": "off",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
        "require-await": "off",
      },
    },
    // ⚛️ [8] React/JSX/accessibility rules
    // Maps to: eslint-plugin-react, react-hooks, and jsx-a11y configs
    // Only applies to JSX/TSX files (component files).
    //
    // Key rules:
    //   - react-hooks/rules-of-hooks + exhaustive-deps (critical for correctness)
    //   - jsx-a11y/* (WCAG accessibility compliance)
    //   - react/jsx-curly-brace-presence (clean JSX syntax)
    //   - react/react-in-jsx-scope: off (React 19 new JSX transform)
    {
      files: ["**/*.jsx", "**/*.tsx"],
      plugins: ["jsx-a11y", "react"],
      rules: {
        "jsx-a11y/alt-text": "error",
        "jsx-a11y/anchor-ambiguous-text": "off",
        "jsx-a11y/anchor-has-content": "error",
        "jsx-a11y/anchor-is-valid": "error",
        "jsx-a11y/aria-activedescendant-has-tabindex": "error",
        "jsx-a11y/aria-props": "error",
        "jsx-a11y/aria-proptypes": "error",
        "jsx-a11y/aria-role": "error",
        "jsx-a11y/aria-unsupported-elements": "error",
        "jsx-a11y/autocomplete-valid": "error",
        "jsx-a11y/click-events-have-key-events": "error",
        "jsx-a11y/heading-has-content": "error",
        "jsx-a11y/html-has-lang": "error",
        "jsx-a11y/iframe-has-title": "error",
        "jsx-a11y/img-redundant-alt": "error",
        "jsx-a11y/label-has-associated-control": "error",
        "jsx-a11y/media-has-caption": "error",
        "jsx-a11y/mouse-events-have-key-events": "error",
        "jsx-a11y/no-access-key": "error",
        "jsx-a11y/no-autofocus": "error",
        "jsx-a11y/no-distracting-elements": "error",
        "jsx-a11y/no-noninteractive-tabindex": [
          "error",
          {
            allowExpressionValues: true,
            roles: ["tabpanel"],
            tags: [],
          },
        ],
        "jsx-a11y/no-redundant-roles": "error",
        "jsx-a11y/no-static-element-interactions": [
          "error",
          {
            allowExpressionValues: true,
            handlers: [
              "onClick",
              "onKeyDown",
              "onKeyPress",
              "onKeyUp",
              "onMouseDown",
              "onMouseUp",
            ],
          },
        ],
        "jsx-a11y/role-has-required-aria-props": "error",
        "jsx-a11y/role-supports-aria-props": "error",
        "jsx-a11y/scope": "error",
        "jsx-a11y/tabindex-no-positive": "error",
        "react-hooks/exhaustive-deps": "error",
        "react-hooks/rules-of-hooks": "error",
        "react/display-name": "error",
        "react/jsx-boolean-value": ["error", "never"],
        "react/jsx-curly-brace-presence": [
          "error",
          {
            children: "never",
            props: "never",
          },
        ],
        "react/jsx-key": "error",
        "react/jsx-no-comment-textnodes": "error",
        "react/jsx-no-duplicate-props": "error",
        "react/jsx-no-target-blank": "error",
        "react/jsx-no-undef": "error",
        "react/jsx-pascal-case": "error",
        "react/no-array-index-key": "warn",
        "react/no-children-prop": "error",
        "react/no-danger-with-children": "error",
        "react/no-direct-mutation-state": "error",
        "react/no-find-dom-node": "error",
        "react/no-is-mounted": "error",
        "react/no-render-return-value": "error",
        "react/no-string-refs": "error",
        "react/no-unescaped-entities": "error",
        "react/no-unknown-property": "error",
        "react/no-unsafe": "off",
        "react/react-in-jsx-scope": "off",
        "react/self-closing-comp": "error",
      },
    },
    // 🧪 [9] Test file relaxations (TypeScript)
    // Relax strictness in test files: allow `any` (warn instead of error)
    // and console.log for debugging test output.
    {
      files: [
        "**/*.spec.ts",
        "**/*.spec.tsx",
        "**/*.test.ts",
        "**/*.test.tsx",
        "**/__tests__/**",
        "**/testing/**",
      ],
      plugins: ["typescript"],
      rules: {
        "@typescript-eslint/no-explicit-any": "warn",
        "no-console": "off",
      },
    },
    // 📄 [10] JS file relaxations (TypeScript rules)
    // JS config files (*.cjs, *.mjs) don't have TypeScript, so disable
    // TS-specific rules: require-imports (CommonJS needs require()),
    // explicit return types, and module boundary types.
    {
      files: ["**/*.cjs", "**/*.js", "**/*.mjs"],
      plugins: ["typescript"],
      rules: {
        "@typescript-eslint/explicit-function-return-type": "off",
        "@typescript-eslint/explicit-module-boundary-types": "off",
        "@typescript-eslint/no-require-imports": "off",
      },
    },
    // 📋 [11] JSON file rules
    // JSON files don't have expressions or variables — disable rules that
    // would produce false positives on JSON syntax.
    {
      files: ["**/*.json", "**/*.json5", "**/*.jsonc"],
      rules: {
        "no-unused-expressions": "off",
        "no-unused-vars": "off",
      },
    },
    // 🗂️ [12] YAML file rules
    // YAML uses significant whitespace differently — disable rules that
    // conflict with YAML syntax (e.g., irregular whitespace is normal in YAML).
    {
      files: ["**/*.yaml", "**/*.yml"],
      rules: {
        "no-irregular-whitespace": "off",
        "no-unused-vars": "off",
      },
    },
  ],
  // 🔌 Plugins
  // Each plugin maps to its ESLint equivalent:
  //   - unicorn → eslint-plugin-unicorn (modern JS best practices)
  //   - react → eslint-plugin-react + eslint-plugin-react-hooks
  //   - typescript → @typescript-eslint/eslint-plugin
  //   - jsx-a11y → eslint-plugin-jsx-a11y (accessibility)
  //   - import → eslint-plugin-import (import/export validation)
  plugins: ["import", "jsx-a11y", "react", "typescript", "unicorn"],
  // No top-level rules — all rules are scoped via overrides for file-type specificity
  rules: {},
});
