import type { CodeStatisticsResult } from "@codometer/core";

/**
 * Builds a zeroed statistics report for tests that only pass one through.
 *
 * Every counter the pipeline produces is present, so a test asserting on the
 * whole report keeps working when a new statistic is added.
 */
export function buildCodeStatistics(
  overrides: Partial<CodeStatisticsResult> = {},
): CodeStatisticsResult {
  return {
    css: {
      atRules: 0,
      comments: 0,
      customProperties: 0,
      declarations: 0,
      files: 0,
      lines: 0,
      mediaQueries: 0,
      rules: 0,
      selectors: 0,
    },
    custom: [],
    folders: 0,
    hcl: {
      attributes: 0,
      blocks: 0,
      comments: 0,
      files: 0,
      interpolations: 0,
      lines: 0,
      outputs: 0,
      resources: 0,
      variables: 0,
    },
    javascript: {
      asyncFunctions: 0,
      classes: 0,
      commentLines: 0,
      comments: 0,
      constants: 0,
      exported: 0,
      externalPackages: 0,
      files: 0,
      functions: 0,
      imports: 0,
      methods: 0,
      syncFunctions: 0,
      testFiles: 0,
      todos: 0,
    },
    json: {
      arrays: 0,
      booleans: 0,
      files: 0,
      items: 0,
      lines: 0,
      maxDepth: 0,
      nulls: 0,
      numbers: 0,
      objects: 0,
      properties: 0,
      strings: 0,
      totalNodes: 0,
    },
    jupyter: {
      cells: 0,
      classes: 0,
      codeBlocks: 0,
      codeCells: 0,
      codeLines: 0,
      decorators: 0,
      executedCells: 0,
      files: 0,
      functions: 0,
      headings: 0,
      images: 0,
      imports: 0,
      links: 0,
      markdownCells: 0,
      markdownLines: 0,
      maxDepth: 0,
      outputs: 0,
      properties: 0,
      rawCells: 0,
      totalNodes: 0,
    },
    linesOfCode: 0,
    markdown: {
      blockQuotes: 0,
      codeBlocks: 0,
      files: 0,
      headingLevel1: 0,
      headingLevel2: 0,
      headingLevel3: 0,
      headingLevel4: 0,
      headingLevel5: 0,
      headingLevel6: 0,
      images: 0,
      inlineCode: 0,
      lines: 0,
      links: 0,
      listItems: 0,
      lists: 0,
      paragraphs: 0,
      tableRows: 0,
      tables: 0,
      taskListItems: 0,
      thematicBreaks: 0,
    },
    python: {
      classes: 0,
      commentLines: 0,
      comments: 0,
      constants: 0,
      decorators: 0,
      docstringLines: 0,
      docstrings: 0,
      files: 0,
      functions: 0,
      imports: 0,
      lines: 0,
      protocols: 0,
    },
    repositoryBytes: 0,
    shell: {
      commentLines: 0,
      comments: 0,
      conditionals: 0,
      exports: 0,
      files: 0,
      functions: 0,
      lines: 0,
      loops: 0,
      pipelines: 0,
      shebangs: 0,
      variables: 0,
    },
    sourceFiles: 0,
    sql: {
      comments: 0,
      commonTableExpressions: 0,
      creates: 0,
      deletes: 0,
      files: 0,
      inserts: 0,
      joins: 0,
      lines: 0,
      selects: 0,
      statements: 0,
      updates: 0,
    },
    toml: {
      arrays: 0,
      arrayTables: 0,
      comments: 0,
      files: 0,
      keys: 0,
      lines: 0,
      tables: 0,
    },
    typescript: {
      decorators: 0,
      docComments: 0,
      enums: 0,
      files: 0,
      genericDeclarations: 0,
      interfaces: 0,
    },
    yaml: {
      aliases: 0,
      anchors: 0,
      comments: 0,
      documents: 0,
      files: 0,
      keys: 0,
      lines: 0,
      mappings: 0,
      maxDepth: 0,
      scalars: 0,
      sequences: 0,
    },
    ...overrides,
  };
}

/**
 * Throws the given value without narrowing it to `Error`.
 *
 * A catch block that special-cases `instanceof Error` needs a thrown value
 * that provably is not one to exercise its other branch. Typing the
 * parameter `unknown` is what lets a test throw a bare string or object
 * without tripping the lint rule that otherwise requires every `throw` to
 * carry an `Error`.
 */
export function throwUnknown(value: unknown): never {
  throw value;
}
