import { PrimaryColumn } from "typeorm";

/**
 * The base every table's entity extends: a `uuid` primary key the database
 * assigns on insert with Postgres 18's native `uuidv7()`, so ids sort by when
 * their rows were written.
 *
 * Generated by the database rather than by TypeORM, which only generates
 * version 4 and skips any per-entity hook on a bulk `insert`.
 */
export abstract class IdentifiableEntity {
  @PrimaryColumn({
    comment: "Primary key, a uuidv7 the database assigns on insert",
    default: () => "uuidv7()",
    type: "uuid",
  })
  id!: string;
}
